(cl:in-package ases_mc_pkg1-srv)
(cl:export '(MODE-VAL
          MODE
          POSITION_X-VAL
          POSITION_X
          POSITION_Y-VAL
          POSITION_Y
          POSITION_Z-VAL
          POSITION_Z
          POSITION_O-VAL
          POSITION_O
          POSITION_G-VAL
          POSITION_G
          POSITION_R-VAL
          POSITION_R
          VELOCITY_X-VAL
          VELOCITY_X
          VELOCITY_Y-VAL
          VELOCITY_Y
          VELOCITY_Z-VAL
          VELOCITY_Z
          VELOCITY_O-VAL
          VELOCITY_O
          VELOCITY_G-VAL
          VELOCITY_G
          VELOCITY_R-VAL
          VELOCITY_R
          SUCCESS-VAL
          SUCCESS
))