deviceName: "EPOS2"
protocolStackName: "MAXON_RS232"
interfaceName: "RS232"
portName: "/dev/ttyS1"
subdeviceName: "EPOS4"
subprotocolStackName: "CANopen"
BaudRate: 0
Timeout: 0
NodeId: 1
sensortype: 1
encoderresolution: 500
invertedpolarity: 0
xaxishomeposoffset: 0
yaxishomeposoffset: 0
zaxishomeposoffset: 0
xcountpermm: 10248 
ycountpermm: 10248 
zcountpermm: 10248 
xparkingpos: 50
yparkingpos: 50
zparkingpos: 50


