// Generated by gencpp from file ases_mc_pkg1/automatic_job.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_AUTOMATIC_JOB_H
#define ASES_MC_PKG1_MESSAGE_AUTOMATIC_JOB_H

#include <ros/service_traits.h>


#include <ases_mc_pkg1/automatic_jobRequest.h>
#include <ases_mc_pkg1/automatic_jobResponse.h>


namespace ases_mc_pkg1
{

struct automatic_job
{

typedef automatic_jobRequest Request;
typedef automatic_jobResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct automatic_job
} // namespace ases_mc_pkg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ases_mc_pkg1::automatic_job > {
  static const char* value()
  {
    return "cfe80a97e30be51ef40c9219e69602d9";
  }

  static const char* value(const ::ases_mc_pkg1::automatic_job&) { return value(); }
};

template<>
struct DataType< ::ases_mc_pkg1::automatic_job > {
  static const char* value()
  {
    return "ases_mc_pkg1/automatic_job";
  }

  static const char* value(const ::ases_mc_pkg1::automatic_job&) { return value(); }
};


// service_traits::MD5Sum< ::ases_mc_pkg1::automatic_jobRequest> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::automatic_job >
template<>
struct MD5Sum< ::ases_mc_pkg1::automatic_jobRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::automatic_job >::value();
  }
  static const char* value(const ::ases_mc_pkg1::automatic_jobRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::automatic_jobRequest> should match
// service_traits::DataType< ::ases_mc_pkg1::automatic_job >
template<>
struct DataType< ::ases_mc_pkg1::automatic_jobRequest>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::automatic_job >::value();
  }
  static const char* value(const ::ases_mc_pkg1::automatic_jobRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ases_mc_pkg1::automatic_jobResponse> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::automatic_job >
template<>
struct MD5Sum< ::ases_mc_pkg1::automatic_jobResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::automatic_job >::value();
  }
  static const char* value(const ::ases_mc_pkg1::automatic_jobResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::automatic_jobResponse> should match
// service_traits::DataType< ::ases_mc_pkg1::automatic_job >
template<>
struct DataType< ::ases_mc_pkg1::automatic_jobResponse>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::automatic_job >::value();
  }
  static const char* value(const ::ases_mc_pkg1::automatic_jobResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_AUTOMATIC_JOB_H
