// Generated by gencpp from file ases_mc_pkg1/automatic_jobRequest.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_AUTOMATIC_JOBREQUEST_H
#define ASES_MC_PKG1_MESSAGE_AUTOMATIC_JOBREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ases_mc_pkg1
{
template <class ContainerAllocator>
struct automatic_jobRequest_
{
  typedef automatic_jobRequest_<ContainerAllocator> Type;

  automatic_jobRequest_()
    : overlap(0)
    , rpm(0.0)
    , job()  {
    }
  automatic_jobRequest_(const ContainerAllocator& _alloc)
    : overlap(0)
    , rpm(0.0)
    , job(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _overlap_type;
  _overlap_type overlap;

   typedef double _rpm_type;
  _rpm_type rpm;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _job_type;
  _job_type job;





  typedef boost::shared_ptr< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> const> ConstPtr;

}; // struct automatic_jobRequest_

typedef ::ases_mc_pkg1::automatic_jobRequest_<std::allocator<void> > automatic_jobRequest;

typedef boost::shared_ptr< ::ases_mc_pkg1::automatic_jobRequest > automatic_jobRequestPtr;
typedef boost::shared_ptr< ::ases_mc_pkg1::automatic_jobRequest const> automatic_jobRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator2> & rhs)
{
  return lhs.overlap == rhs.overlap &&
    lhs.rpm == rhs.rpm &&
    lhs.job == rhs.job;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ases_mc_pkg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac02e20925030f595af8d6004016c5d5";
  }

  static const char* value(const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac02e20925030f59ULL;
  static const uint64_t static_value2 = 0x5af8d6004016c5d5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ases_mc_pkg1/automatic_jobRequest";
  }

  static const char* value(const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 overlap\n"
"float64 rpm\n"
"string job\n"
;
  }

  static const char* value(const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.overlap);
      stream.next(m.rpm);
      stream.next(m.job);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct automatic_jobRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ases_mc_pkg1::automatic_jobRequest_<ContainerAllocator>& v)
  {
    s << indent << "overlap: ";
    Printer<int64_t>::stream(s, indent + "  ", v.overlap);
    s << indent << "rpm: ";
    Printer<double>::stream(s, indent + "  ", v.rpm);
    s << indent << "job: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.job);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_AUTOMATIC_JOBREQUEST_H
