// Generated by gencpp from file ases_mc_pkg1/axis_motion.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_AXIS_MOTION_H
#define ASES_MC_PKG1_MESSAGE_AXIS_MOTION_H

#include <ros/service_traits.h>


#include <ases_mc_pkg1/axis_motionRequest.h>
#include <ases_mc_pkg1/axis_motionResponse.h>


namespace ases_mc_pkg1
{

struct axis_motion
{

typedef axis_motionRequest Request;
typedef axis_motionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct axis_motion
} // namespace ases_mc_pkg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ases_mc_pkg1::axis_motion > {
  static const char* value()
  {
    return "c335753bd65b2110697b8c82c9ecf78e";
  }

  static const char* value(const ::ases_mc_pkg1::axis_motion&) { return value(); }
};

template<>
struct DataType< ::ases_mc_pkg1::axis_motion > {
  static const char* value()
  {
    return "ases_mc_pkg1/axis_motion";
  }

  static const char* value(const ::ases_mc_pkg1::axis_motion&) { return value(); }
};


// service_traits::MD5Sum< ::ases_mc_pkg1::axis_motionRequest> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::axis_motion >
template<>
struct MD5Sum< ::ases_mc_pkg1::axis_motionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::axis_motion >::value();
  }
  static const char* value(const ::ases_mc_pkg1::axis_motionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::axis_motionRequest> should match
// service_traits::DataType< ::ases_mc_pkg1::axis_motion >
template<>
struct DataType< ::ases_mc_pkg1::axis_motionRequest>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::axis_motion >::value();
  }
  static const char* value(const ::ases_mc_pkg1::axis_motionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ases_mc_pkg1::axis_motionResponse> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::axis_motion >
template<>
struct MD5Sum< ::ases_mc_pkg1::axis_motionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::axis_motion >::value();
  }
  static const char* value(const ::ases_mc_pkg1::axis_motionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::axis_motionResponse> should match
// service_traits::DataType< ::ases_mc_pkg1::axis_motion >
template<>
struct DataType< ::ases_mc_pkg1::axis_motionResponse>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::axis_motion >::value();
  }
  static const char* value(const ::ases_mc_pkg1::axis_motionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_AXIS_MOTION_H
