// Generated by gencpp from file ases_mc_pkg1/grip_releaseRequest.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_GRIP_RELEASEREQUEST_H
#define ASES_MC_PKG1_MESSAGE_GRIP_RELEASEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ases_mc_pkg1
{
template <class ContainerAllocator>
struct grip_releaseRequest_
{
  typedef grip_releaseRequest_<ContainerAllocator> Type;

  grip_releaseRequest_()
    : command()  {
    }
  grip_releaseRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct grip_releaseRequest_

typedef ::ases_mc_pkg1::grip_releaseRequest_<std::allocator<void> > grip_releaseRequest;

typedef boost::shared_ptr< ::ases_mc_pkg1::grip_releaseRequest > grip_releaseRequestPtr;
typedef boost::shared_ptr< ::ases_mc_pkg1::grip_releaseRequest const> grip_releaseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ases_mc_pkg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ases_mc_pkg1/grip_releaseRequest";
  }

  static const char* value(const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
;
  }

  static const char* value(const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grip_releaseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ases_mc_pkg1::grip_releaseRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_GRIP_RELEASEREQUEST_H
