// Generated by gencpp from file ases_mc_pkg1/grip_release.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_GRIP_RELEASE_H
#define ASES_MC_PKG1_MESSAGE_GRIP_RELEASE_H

#include <ros/service_traits.h>


#include <ases_mc_pkg1/grip_releaseRequest.h>
#include <ases_mc_pkg1/grip_releaseResponse.h>


namespace ases_mc_pkg1
{

struct grip_release
{

typedef grip_releaseRequest Request;
typedef grip_releaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct grip_release
} // namespace ases_mc_pkg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ases_mc_pkg1::grip_release > {
  static const char* value()
  {
    return "031d24522d462b2314fd1b6270670dd2";
  }

  static const char* value(const ::ases_mc_pkg1::grip_release&) { return value(); }
};

template<>
struct DataType< ::ases_mc_pkg1::grip_release > {
  static const char* value()
  {
    return "ases_mc_pkg1/grip_release";
  }

  static const char* value(const ::ases_mc_pkg1::grip_release&) { return value(); }
};


// service_traits::MD5Sum< ::ases_mc_pkg1::grip_releaseRequest> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::grip_release >
template<>
struct MD5Sum< ::ases_mc_pkg1::grip_releaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::grip_release >::value();
  }
  static const char* value(const ::ases_mc_pkg1::grip_releaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::grip_releaseRequest> should match
// service_traits::DataType< ::ases_mc_pkg1::grip_release >
template<>
struct DataType< ::ases_mc_pkg1::grip_releaseRequest>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::grip_release >::value();
  }
  static const char* value(const ::ases_mc_pkg1::grip_releaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ases_mc_pkg1::grip_releaseResponse> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::grip_release >
template<>
struct MD5Sum< ::ases_mc_pkg1::grip_releaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::grip_release >::value();
  }
  static const char* value(const ::ases_mc_pkg1::grip_releaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::grip_releaseResponse> should match
// service_traits::DataType< ::ases_mc_pkg1::grip_release >
template<>
struct DataType< ::ases_mc_pkg1::grip_releaseResponse>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::grip_release >::value();
  }
  static const char* value(const ::ases_mc_pkg1::grip_releaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_GRIP_RELEASE_H
