// Generated by gencpp from file ases_mc_pkg1/homing_axis_srv.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRV_H
#define ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRV_H

#include <ros/service_traits.h>


#include <ases_mc_pkg1/homing_axis_srvRequest.h>
#include <ases_mc_pkg1/homing_axis_srvResponse.h>


namespace ases_mc_pkg1
{

struct homing_axis_srv
{

typedef homing_axis_srvRequest Request;
typedef homing_axis_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct homing_axis_srv
} // namespace ases_mc_pkg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ases_mc_pkg1::homing_axis_srv > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::ases_mc_pkg1::homing_axis_srv&) { return value(); }
};

template<>
struct DataType< ::ases_mc_pkg1::homing_axis_srv > {
  static const char* value()
  {
    return "ases_mc_pkg1/homing_axis_srv";
  }

  static const char* value(const ::ases_mc_pkg1::homing_axis_srv&) { return value(); }
};


// service_traits::MD5Sum< ::ases_mc_pkg1::homing_axis_srvRequest> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::homing_axis_srv >
template<>
struct MD5Sum< ::ases_mc_pkg1::homing_axis_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::homing_axis_srv >::value();
  }
  static const char* value(const ::ases_mc_pkg1::homing_axis_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::homing_axis_srvRequest> should match
// service_traits::DataType< ::ases_mc_pkg1::homing_axis_srv >
template<>
struct DataType< ::ases_mc_pkg1::homing_axis_srvRequest>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::homing_axis_srv >::value();
  }
  static const char* value(const ::ases_mc_pkg1::homing_axis_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ases_mc_pkg1::homing_axis_srvResponse> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::homing_axis_srv >
template<>
struct MD5Sum< ::ases_mc_pkg1::homing_axis_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::homing_axis_srv >::value();
  }
  static const char* value(const ::ases_mc_pkg1::homing_axis_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::homing_axis_srvResponse> should match
// service_traits::DataType< ::ases_mc_pkg1::homing_axis_srv >
template<>
struct DataType< ::ases_mc_pkg1::homing_axis_srvResponse>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::homing_axis_srv >::value();
  }
  static const char* value(const ::ases_mc_pkg1::homing_axis_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRV_H
