// Generated by gencpp from file ases_mc_pkg1/homing_axis_srvRequest.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRVREQUEST_H
#define ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ases_mc_pkg1
{
template <class ContainerAllocator>
struct homing_axis_srvRequest_
{
  typedef homing_axis_srvRequest_<ContainerAllocator> Type;

  homing_axis_srvRequest_()
    {
    }
  homing_axis_srvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct homing_axis_srvRequest_

typedef ::ases_mc_pkg1::homing_axis_srvRequest_<std::allocator<void> > homing_axis_srvRequest;

typedef boost::shared_ptr< ::ases_mc_pkg1::homing_axis_srvRequest > homing_axis_srvRequestPtr;
typedef boost::shared_ptr< ::ases_mc_pkg1::homing_axis_srvRequest const> homing_axis_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace ases_mc_pkg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ases_mc_pkg1/homing_axis_srvRequest";
  }

  static const char* value(const ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct homing_axis_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ases_mc_pkg1::homing_axis_srvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRVREQUEST_H
