// Generated by gencpp from file ases_mc_pkg1/homing_axis_srvResponse.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRVRESPONSE_H
#define ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ases_mc_pkg1
{
template <class ContainerAllocator>
struct homing_axis_srvResponse_
{
  typedef homing_axis_srvResponse_<ContainerAllocator> Type;

  homing_axis_srvResponse_()
    : success(false)  {
    }
  homing_axis_srvResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct homing_axis_srvResponse_

typedef ::ases_mc_pkg1::homing_axis_srvResponse_<std::allocator<void> > homing_axis_srvResponse;

typedef boost::shared_ptr< ::ases_mc_pkg1::homing_axis_srvResponse > homing_axis_srvResponsePtr;
typedef boost::shared_ptr< ::ases_mc_pkg1::homing_axis_srvResponse const> homing_axis_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ases_mc_pkg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ases_mc_pkg1/homing_axis_srvResponse";
  }

  static const char* value(const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct homing_axis_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ases_mc_pkg1::homing_axis_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_HOMING_AXIS_SRVRESPONSE_H
