// Generated by gencpp from file ases_mc_pkg1/laser_controlRequest.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_LASER_CONTROLREQUEST_H
#define ASES_MC_PKG1_MESSAGE_LASER_CONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ases_mc_pkg1
{
template <class ContainerAllocator>
struct laser_controlRequest_
{
  typedef laser_controlRequest_<ContainerAllocator> Type;

  laser_controlRequest_()
    : cmd_lasercontrol()  {
    }
  laser_controlRequest_(const ContainerAllocator& _alloc)
    : cmd_lasercontrol(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_lasercontrol_type;
  _cmd_lasercontrol_type cmd_lasercontrol;





  typedef boost::shared_ptr< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct laser_controlRequest_

typedef ::ases_mc_pkg1::laser_controlRequest_<std::allocator<void> > laser_controlRequest;

typedef boost::shared_ptr< ::ases_mc_pkg1::laser_controlRequest > laser_controlRequestPtr;
typedef boost::shared_ptr< ::ases_mc_pkg1::laser_controlRequest const> laser_controlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd_lasercontrol == rhs.cmd_lasercontrol;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ases_mc_pkg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d324c2a313cd6bae1b1c064d94313788";
  }

  static const char* value(const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd324c2a313cd6baeULL;
  static const uint64_t static_value2 = 0x1b1c064d94313788ULL;
};

template<class ContainerAllocator>
struct DataType< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ases_mc_pkg1/laser_controlRequest";
  }

  static const char* value(const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cmd_lasercontrol\n"
;
  }

  static const char* value(const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_lasercontrol);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct laser_controlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ases_mc_pkg1::laser_controlRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd_lasercontrol: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd_lasercontrol);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_LASER_CONTROLREQUEST_H
