// Generated by gencpp from file ases_mc_pkg1/laser_control.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_LASER_CONTROL_H
#define ASES_MC_PKG1_MESSAGE_LASER_CONTROL_H

#include <ros/service_traits.h>


#include <ases_mc_pkg1/laser_controlRequest.h>
#include <ases_mc_pkg1/laser_controlResponse.h>


namespace ases_mc_pkg1
{

struct laser_control
{

typedef laser_controlRequest Request;
typedef laser_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct laser_control
} // namespace ases_mc_pkg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ases_mc_pkg1::laser_control > {
  static const char* value()
  {
    return "e3f9c60fce0f55c2b7eb3a8b43ae70da";
  }

  static const char* value(const ::ases_mc_pkg1::laser_control&) { return value(); }
};

template<>
struct DataType< ::ases_mc_pkg1::laser_control > {
  static const char* value()
  {
    return "ases_mc_pkg1/laser_control";
  }

  static const char* value(const ::ases_mc_pkg1::laser_control&) { return value(); }
};


// service_traits::MD5Sum< ::ases_mc_pkg1::laser_controlRequest> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::laser_control >
template<>
struct MD5Sum< ::ases_mc_pkg1::laser_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::laser_control >::value();
  }
  static const char* value(const ::ases_mc_pkg1::laser_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::laser_controlRequest> should match
// service_traits::DataType< ::ases_mc_pkg1::laser_control >
template<>
struct DataType< ::ases_mc_pkg1::laser_controlRequest>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::laser_control >::value();
  }
  static const char* value(const ::ases_mc_pkg1::laser_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ases_mc_pkg1::laser_controlResponse> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::laser_control >
template<>
struct MD5Sum< ::ases_mc_pkg1::laser_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::laser_control >::value();
  }
  static const char* value(const ::ases_mc_pkg1::laser_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::laser_controlResponse> should match
// service_traits::DataType< ::ases_mc_pkg1::laser_control >
template<>
struct DataType< ::ases_mc_pkg1::laser_controlResponse>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::laser_control >::value();
  }
  static const char* value(const ::ases_mc_pkg1::laser_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_LASER_CONTROL_H
