// Generated by gencpp from file ases_mc_pkg1/parkingRequest.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_PARKINGREQUEST_H
#define ASES_MC_PKG1_MESSAGE_PARKINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ases_mc_pkg1
{
template <class ContainerAllocator>
struct parkingRequest_
{
  typedef parkingRequest_<ContainerAllocator> Type;

  parkingRequest_()
    : start(false)  {
    }
  parkingRequest_(const ContainerAllocator& _alloc)
    : start(false)  {
  (void)_alloc;
    }



   typedef uint8_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct parkingRequest_

typedef ::ases_mc_pkg1::parkingRequest_<std::allocator<void> > parkingRequest;

typedef boost::shared_ptr< ::ases_mc_pkg1::parkingRequest > parkingRequestPtr;
typedef boost::shared_ptr< ::ases_mc_pkg1::parkingRequest const> parkingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ases_mc_pkg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "676aa7bfb3ec2071e814f2368dfd5fb5";
  }

  static const char* value(const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x676aa7bfb3ec2071ULL;
  static const uint64_t static_value2 = 0xe814f2368dfd5fb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ases_mc_pkg1/parkingRequest";
  }

  static const char* value(const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool start\n"
;
  }

  static const char* value(const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct parkingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ases_mc_pkg1::parkingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ases_mc_pkg1::parkingRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_PARKINGREQUEST_H
