// Generated by gencpp from file ases_mc_pkg1/parking.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_PARKING_H
#define ASES_MC_PKG1_MESSAGE_PARKING_H

#include <ros/service_traits.h>


#include <ases_mc_pkg1/parkingRequest.h>
#include <ases_mc_pkg1/parkingResponse.h>


namespace ases_mc_pkg1
{

struct parking
{

typedef parkingRequest Request;
typedef parkingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct parking
} // namespace ases_mc_pkg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ases_mc_pkg1::parking > {
  static const char* value()
  {
    return "bbb7ba84302b6f35af5466a95cd7ac90";
  }

  static const char* value(const ::ases_mc_pkg1::parking&) { return value(); }
};

template<>
struct DataType< ::ases_mc_pkg1::parking > {
  static const char* value()
  {
    return "ases_mc_pkg1/parking";
  }

  static const char* value(const ::ases_mc_pkg1::parking&) { return value(); }
};


// service_traits::MD5Sum< ::ases_mc_pkg1::parkingRequest> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::parking >
template<>
struct MD5Sum< ::ases_mc_pkg1::parkingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::parking >::value();
  }
  static const char* value(const ::ases_mc_pkg1::parkingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::parkingRequest> should match
// service_traits::DataType< ::ases_mc_pkg1::parking >
template<>
struct DataType< ::ases_mc_pkg1::parkingRequest>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::parking >::value();
  }
  static const char* value(const ::ases_mc_pkg1::parkingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ases_mc_pkg1::parkingResponse> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::parking >
template<>
struct MD5Sum< ::ases_mc_pkg1::parkingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::parking >::value();
  }
  static const char* value(const ::ases_mc_pkg1::parkingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::parkingResponse> should match
// service_traits::DataType< ::ases_mc_pkg1::parking >
template<>
struct DataType< ::ases_mc_pkg1::parkingResponse>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::parking >::value();
  }
  static const char* value(const ::ases_mc_pkg1::parkingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_PARKING_H
