// Generated by gencpp from file ases_mc_pkg1/welding.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_WELDING_H
#define ASES_MC_PKG1_MESSAGE_WELDING_H

#include <ros/service_traits.h>


#include <ases_mc_pkg1/weldingRequest.h>
#include <ases_mc_pkg1/weldingResponse.h>


namespace ases_mc_pkg1
{

struct welding
{

typedef weldingRequest Request;
typedef weldingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct welding
} // namespace ases_mc_pkg1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ases_mc_pkg1::welding > {
  static const char* value()
  {
    return "0d4d374987d43cb065ea6a57001df011";
  }

  static const char* value(const ::ases_mc_pkg1::welding&) { return value(); }
};

template<>
struct DataType< ::ases_mc_pkg1::welding > {
  static const char* value()
  {
    return "ases_mc_pkg1/welding";
  }

  static const char* value(const ::ases_mc_pkg1::welding&) { return value(); }
};


// service_traits::MD5Sum< ::ases_mc_pkg1::weldingRequest> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::welding >
template<>
struct MD5Sum< ::ases_mc_pkg1::weldingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::welding >::value();
  }
  static const char* value(const ::ases_mc_pkg1::weldingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::weldingRequest> should match
// service_traits::DataType< ::ases_mc_pkg1::welding >
template<>
struct DataType< ::ases_mc_pkg1::weldingRequest>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::welding >::value();
  }
  static const char* value(const ::ases_mc_pkg1::weldingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ases_mc_pkg1::weldingResponse> should match
// service_traits::MD5Sum< ::ases_mc_pkg1::welding >
template<>
struct MD5Sum< ::ases_mc_pkg1::weldingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ases_mc_pkg1::welding >::value();
  }
  static const char* value(const ::ases_mc_pkg1::weldingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ases_mc_pkg1::weldingResponse> should match
// service_traits::DataType< ::ases_mc_pkg1::welding >
template<>
struct DataType< ::ases_mc_pkg1::weldingResponse>
{
  static const char* value()
  {
    return DataType< ::ases_mc_pkg1::welding >::value();
  }
  static const char* value(const ::ases_mc_pkg1::weldingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_WELDING_H
