// Generated by gencpp from file ases_mc_pkg1/weldingRequest.msg
// DO NOT EDIT!


#ifndef ASES_MC_PKG1_MESSAGE_WELDINGREQUEST_H
#define ASES_MC_PKG1_MESSAGE_WELDINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ases_mc_pkg1
{
template <class ContainerAllocator>
struct weldingRequest_
{
  typedef weldingRequest_<ContainerAllocator> Type;

  weldingRequest_()
    : cmd_welding()  {
    }
  weldingRequest_(const ContainerAllocator& _alloc)
    : cmd_welding(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _cmd_welding_type;
  _cmd_welding_type cmd_welding;





  typedef boost::shared_ptr< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct weldingRequest_

typedef ::ases_mc_pkg1::weldingRequest_<std::allocator<void> > weldingRequest;

typedef boost::shared_ptr< ::ases_mc_pkg1::weldingRequest > weldingRequestPtr;
typedef boost::shared_ptr< ::ases_mc_pkg1::weldingRequest const> weldingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd_welding == rhs.cmd_welding;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator1> & lhs, const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ases_mc_pkg1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "384019d8885c283bef498653abb3ad57";
  }

  static const char* value(const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x384019d8885c283bULL;
  static const uint64_t static_value2 = 0xef498653abb3ad57ULL;
};

template<class ContainerAllocator>
struct DataType< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ases_mc_pkg1/weldingRequest";
  }

  static const char* value(const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string cmd_welding\n"
;
  }

  static const char* value(const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_welding);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct weldingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ases_mc_pkg1::weldingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ases_mc_pkg1::weldingRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd_welding: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.cmd_welding);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASES_MC_PKG1_MESSAGE_WELDINGREQUEST_H
